### ISSUE TITLE
适配 lua5.4

### ISSUE THREAD

**Issue by cloudfreexiao** [spin6lock/skynet_systemtap_set#4]
请教下 skynet 已经用到 5.4 了 是否能 适配 lua5.4 ？

**Comment by spin6lock** [comment]
[偶然看到有分享5.4适配的文章，供参考](https://blog.csdn.net/yuanfengyun/article/details/123802836)
目前用的比较少，这个是针对整个进程的，难以定位到指定服务上看火焰图，所以用的比较少了

**Comment by cloudfreexiao** [comment]
好的
